spring:
 application:
  name: 27_Stock_App_Config Server
 datasource:
  url: jdbc:mysql://localhost:3306/stockdb
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
 jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties:
   hibernate:
     dialect: org.hibernate.dialect.MySQLDialect 
    
